# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TalentEdgeApp' do
    
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TalentEdgeApp

    pod ‘ASExtendedCircularMenu’, :git => 'https://github.com/anshul18895/ASExtendedCircularMenu'
    pod 'Charts'
    pod 'CalendarKit', '0.1.22'
    #pod 'CalendarKit'
    pod 'Alamofire'
	pod 'AlamofireImage'
	pod 'Cosmos', git: 'https://github.com/marketplacer/Cosmos.git', tag: '8.0.2'
	pod 'MBCircularProgressBar'
	pod 'SkyFloatingLabelTextField'
	pod 'IQKeyboardManagerSwift', '4.0.10'
	pod 'SwiftyJSON'
	pod 'PageMenu'
    pod 'NextGrowingTextView'
    pod 'MXSegmentedPager'
    pod 'NVActivityIndicatorView'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.1'
            end
        end
    end

end


